### ISSUE TITLE
Can't able to run on swift 2.0

### ISSUE THREAD

**Issue by jimAnderson007** [FahimF/SQLiteDB#23]
Can't able to run on swift 2.0.

If possible then upgrade it for swift 2.0

**Comment by bfernandesbfs** [comment]
Hi 
change the following code from 

private let SQLITE_STATIC = sqlite3_destructor_type(COpaquePointer(bitPattern:0))
private let SQLITE_TRANSIENT = sqlite3_destructor_type(COpaquePointer(bitPattern:-1))

to 
internal let SQLITE_STATIC = unsafeBitCast(0, sqlite3_destructor_type.self)
internal let SQLITE_TRANSIENT = unsafeBitCast(-1, sqlite3_destructor_type.self)

then correct the basic errors for swift 2.0

=)

**Comment by jimAnderson007** [comment]
Thank you so much for quick response.

It's work for me.
