### ISSUE TITLE
Its not working with swift 2.0

### ISSUE THREAD

**Issue by yanctrindade** [FahimF/SQLiteDB#24]
"Cannot invoke initializer for type 'sqlite3_destructor_type'with an argument list of type '(COparquePointer)'

for lines 
private let SQLITE_STATIC = sqlite3_destructor_type(COpaquePointer(bitPattern:0))
private let SQLITE_TRANSIENT = sqlite3_destructor_type(COpaquePointer(bitPattern:-1))

on SQLiteDB.swift

**Comment by jincon** [comment]
you can try  https://github.com/jincon/SQLiteDB_Swift2.0

**Comment by FahimF** [comment]
The project has already been updated here for Swift 2.0 - hence me closing the issue.
