### ISSUE TITLE
Support for Swift 3.0 ? 

### ISSUE THREAD

**Issue by sanskarvihin** [FahimF/SQLiteDB#27]
Hi,

Nice work providing abstraction on Sqlite.! I am trying to integrate SQLiteDB into Mac OS Project, that uses Swift 3.0. Is there any work around for that ?

**Comment by FahimF** [comment]
Swift 3.0 support is coming soon - today's commit is a prelude to moving to Swift 3.0. Just a matter of trying to juggle both Swift 2.x and 3.x branches. I will probably add 3.0 support as a separate branch in the coming week.
