### ISSUE TITLE
Value of type String has no member "positionOf"

### ISSUE THREAD

**Issue by entttom** [FahimF/SQLiteDB#28]
When i try to compile the Code  (XCode 8) i get an Error for the Line  			
let pos = tmp.positionOf(sub:"(")

Value of type String has no member "positionOf".
Is something wrong with the Code or with my setup?
Anyone else have this issue?

`//		NSLog("SQLiteDB - Got column type: \(buf)")
		if buf != nil {
			var tmp = String(validatingUTF8:buf!)!.uppercased()
			// Remove brackets
			let pos = tmp.positionOf(sub:"(")
			if pos > 0 {
				tmp = tmp.subString(start:0, length:pos)
			}`

**Comment by FahimF** [comment]
You are probably missing the String-Extras.swift file which has a few additional String methods. If you update to the latest version, the String-Extras.swift dependency has been removed from the code.
