### ISSUE TITLE
Swift 3 Xcode 8.0 (8A218a) don't compile

### ISSUE THREAD

**Issue by jmanoel** [FahimF/SQLiteDB#29]
Hello.
While I'm trying to compile on swift 3 I have some issues.

Undefined symbols for architecture x86_64:
  "_sqlite3_bind_blob", referenced from:
      Guia_Itapipoca.SQLiteDB.(prepare in _2D93D55DF1AC88576925A27A6918D34B) (sql : Swift.String, params : [Any]?) -> Swift.OpaquePointer? in SQLiteDB.o
  "_sqlite3_bind_double", referenced from:
      Guia_Itapipoca.SQLiteDB.(prepare in _2D93D55DF1AC88576925A27A6918D34B) (sql : Swift.String, params : [Any]?) -> Swift.OpaquePointer? in SQLiteDB.o
  "_sqlite3_bind_int", referenced from:
      Guia_Itapipoca.SQLiteDB.(prepare in _2D93D55DF1AC88576925A27A6918D34B) (sql : Swift.String, params : [Any]?) -> Swift.OpaquePointer? in SQLiteDB.o
  "_sqlite3_bind_null", referenced from:
      Guia_Itapipoca.SQLiteDB.(prepare in _2D93D55DF1AC88576925A27A6918D34B) (sql : Swift.String, params : [Any]?) -> Swift.OpaquePointer? in SQLiteDB.o
  "_sqlite3_bind_parameter_count", referenced from:
      Guia_Itapipoca.SQLiteDB.(prepare in _2D93D55DF1AC88576925A27A6918D34B) (sql : Swift.String, params : [Any]?) -> Swift.OpaquePointer? in SQLiteDB.o
  "_sqlite3_bind_text", referenced from:
      Guia_Itapipoca.SQLiteDB.(prepare in _2D93D55DF1AC88576925A27A6918D34B) (sql : Swift.String, params : [Any]?) -> Swift.OpaquePointer? in SQLiteDB.o
  "_sqlite3_changes", referenced from:
      Guia_Itapipoca.SQLiteDB.(execute in _2D93D55DF1AC88576925A27A6918D34B) (stmt : Swift.OpaquePointer, sql : Swift.String) -> Swift.Int32 in SQLiteDB.o
  "_sqlite3_close", referenced from:
      Guia_Itapipoca.SQLiteDB.(openDB in _2D93D55DF1AC88576925A27A6918D34B) (path : Swift.String) -> () in SQLiteDB.o
      Guia_Itapipoca.SQLiteDB.(closeDB in _2D93D55DF1AC88576925A27A6918D34B) () -> () in SQLiteDB.o
  "_sqlite3_column_blob", referenced from:
      Guia_Itapipoca.SQLiteDB.(getColumnValue in _2D93D55DF1AC88576925A27A6918D34B) (index : Swift.Int32, type : Swift.Int32, stmt : Swift.OpaquePointer) -> Any? in SQLiteDB.o
  "_sqlite3_column_bytes", referenced from:
      Guia_Itapipoca.SQLiteDB.(getColumnValue in _2D93D55DF1AC88576925A27A6918D34B) (index : Swift.Int32, type : Swift.Int32, stmt : Swift.OpaquePointer) -> Any? in SQLiteDB.o
  "_sqlite3_column_count", referenced from:
      Guia_Itapipoca.SQLiteDB.(query in _2D93D55DF1AC88576925A27A6918D34B) (stmt : Swift.OpaquePointer, sql : Swift.String) -> [[Swift.String : Any]] in SQLiteDB.o
  "_sqlite3_column_decltype", referenced from:
      Guia_Itapipoca.SQLiteDB.(getColumnType in _2D93D55DF1AC88576925A27A6918D34B) (index : Swift.Int32, stmt : Swift.OpaquePointer) -> Swift.Int32 in SQLiteDB.o
  "_sqlite3_column_double", referenced from:
      Guia_Itapipoca.SQLiteDB.(getColumnValue in _2D93D55DF1AC88576925A27A6918D34B) (index : Swift.Int32, type : Swift.Int32, stmt : Swift.OpaquePointer) -> Any? in SQLiteDB.o
  "_sqlite3_column_int", referenced from:
      Guia_Itapipoca.SQLiteDB.(getColumnValue in _2D93D55DF1AC88576925A27A6918D34B) (index : Swift.Int32, type : Swift.Int32, stmt : Swift.OpaquePointer) -> Any? in SQLiteDB.o
  "_sqlite3_column_name", referenced from:
      Guia_Itapipoca.SQLiteDB.(query in _2D93D55DF1AC88576925A27A6918D34B) (stmt : Swift.OpaquePointer, sql : Swift.String) -> [[Swift.String : Any]] in SQLiteDB.o
  "_sqlite3_column_text", referenced from:
      Guia_Itapipoca.SQLiteDB.(getColumnValue in _2D93D55DF1AC88576925A27A6918D34B) (index : Swift.Int32, type : Swift.Int32, stmt : Swift.OpaquePointer) -> Any? in SQLiteDB.o
  "_sqlite3_column_type", referenced from:
      Guia_Itapipoca.SQLiteDB.(getColumnType in _2D93D55DF1AC88576925A27A6918D34B) (index : Swift.Int32, stmt : Swift.OpaquePointer) -> Swift.Int32 in SQLiteDB.o
  "_sqlite3_errmsg", referenced from:
      Guia_Itapipoca.SQLiteDB.(prepare in _2D93D55DF1AC88576925A27A6918D34B) (sql : Swift.String, params : [Any]?) -> Swift.OpaquePointer? in SQLiteDB.o
      Guia_Itapipoca.SQLiteDB.(execute in _2D93D55DF1AC88576925A27A6918D34B) (stmt : Swift.OpaquePointer, sql : Swift.String) -> Swift.Int32 in SQLiteDB.o
  "_sqlite3_finalize", referenced from:
      Guia_Itapipoca.SQLiteDB.(prepare in _2D93D55DF1AC88576925A27A6918D34B) (sql : Swift.String, params : [Any]?) -> Swift.OpaquePointer? in SQLiteDB.o
      Guia_Itapipoca.SQLiteDB.(execute in _2D93D55DF1AC88576925A27A6918D34B) (stmt : Swift.OpaquePointer, sql : Swift.String) -> Swift.Int32 in SQLiteDB.o
      Guia_Itapipoca.SQLiteDB.(query in _2D93D55DF1AC88576925A27A6918D34B) (stmt : Swift.OpaquePointer, sql : Swift.String) -> [[Swift.String : Any]] in SQLiteDB.o
  "_sqlite3_last_insert_rowid", referenced from:
      Guia_Itapipoca.SQLiteDB.(execute in _2D93D55DF1AC88576925A27A6918D34B) (stmt : Swift.OpaquePointer, sql : Swift.String) -> Swift.Int32 in SQLiteDB.o
  "_sqlite3_open", referenced from:
      Guia_Itapipoca.SQLiteDB.(openDB in _2D93D55DF1AC88576925A27A6918D34B) (path : Swift.String) -> () in SQLiteDB.o
  "_sqlite3_prepare_v2", referenced from:
      Guia_Itapipoca.SQLiteDB.(prepare in _2D93D55DF1AC88576925A27A6918D34B) (sql : Swift.String, params : [Any]?) -> Swift.OpaquePointer? in SQLiteDB.o
  "_sqlite3_step", referenced from:
      Guia_Itapipoca.SQLiteDB.(execute in _2D93D55DF1AC88576925A27A6918D34B) (stmt : Swift.OpaquePointer, sql : Swift.String) -> Swift.Int32 in SQLiteDB.o
      Guia_Itapipoca.SQLiteDB.(query in _2D93D55DF1AC88576925A27A6918D34B) (stmt : Swift.OpaquePointer, sql : Swift.String) -> [[Swift.String : Any]] in SQLiteDB.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by FahimF** [comment]
You probably did not include the sqlite3.tdb file as mentioned in the instructions. Or, you did not add the bridging header file with the necessary SQLite import.
