### ISSUE TITLE
Regarding Existing Database

### ISSUE THREAD

**Issue by mohamamdkalim** [FahimF/SQLiteDB#30]
Hello,

Can i use existing database suppose i have songs.sqlite which have lots of table and meta data inside can i used in your db wrapper ?

Because [stephencelis](https://github.com/stephencelis/SQLite.swift) has make a new copy of the database.

Please help me out i am very thankful

Thanks.

**Comment by FahimF** [comment]
Yes you can use existing data but the SQLite database has to be named data.db and has to be included as a resource in the project. Look at the installation documentation to see how that part works.
