### ISSUE TITLE
Is there a way to add a key for cipher?

### ISSUE THREAD

**Issue by abdallahnh** [FahimF/SQLiteDB#33]
Hi @FahimF 

your library is awesome and i would like to use it but my db is encrypted so is there a way to add a decryption for this library?

Thanks.

**Comment by FahimF** [comment]
The source is freely available - so feel free to add the functionality you need :) Unfortunately, I don't foresee adding decryption myself in the near future since I'm a bit busy at the moment.

**Comment by abdallahnh** [comment]
Thx
