### ISSUE TITLE
Error in Ipad IOS 10.1

### ISSUE THREAD

**Issue by gian123** [FahimF/SQLiteDB#34]
When I test my app on Ipad with the version IOS 10.1  shows an error

  let data = db.query(sql: "SELECT * FROM Catalog WHERE id=\(id)")   <--this line is null , in ihpone work fine
        
func query(sql:String, parameters:[Any]?=nil)->[[String:Any]] {
		var rows = [[String:Any]]()
		queue.sync() {
			if let stmt = self.prepare(sql:sql, params:parameters) {
				rows = self.query(stmt:stmt, sql:sql)
			}
		}
		return rows
	}

my db file is on my folder path

help me pleasee
thank for your attention

**Comment by FahimF** [comment]
This does not sound like an SQLiteDB issue. What do you mean when you point to a line of your code and say that the line is null? Do you mean the result from the query is null? Or that the id passed to the SQL string is null?

**Comment by gian123** [comment]
Thanks a lot , is not an issue, is because my project doesn't included  my DB file..=)
