### ISSUE TITLE
Documentation not consistent with example.

### ISSUE THREAD

**Issue by sicaboy** [FahimF/SQLiteDB#37]
For example,
Deleting entry:
Doc way:
    let result = db.execute("DELETE FROM customers WHERE id=1")
Example way:
   _ = TableClass.rowByID(rid: 1)?.delete()

**Comment by FahimF** [comment]
You can use both methods and they work. So it's up to you which way you go. The SQLTable is a new class which allow you to represent a SQLite table as a class. It's functionality is not very well documented, that's true. However, the examples are there to give somebody who is interested a way to figure out the functionality of the class by looking at the source. It's up to you which way you choose.
