### ISSUE TITLE
Generics? Nil support?

### ISSUE THREAD

**Issue by nadav96** [FahimF/SQLiteDB#39]
Hi! Have you thought about making the result rows generic, so it will be nicer to access properties inside of them?
Current syntax:
`let id = rows[0]["id"] as! Int`

Maybe something like
`let id: Int? = rows[0]["id"]`

**Comment by FahimF** [comment]
There are no plans at the moment to support generics since I am not sure how that would interact with SQLTable functionality. But if you want to do the changes and send in a PR, I can take a look at it and see if it can be merged in.
