### ISSUE TITLE
How to create new table in github project

### ISSUE THREAD

**Issue by NiteshKhandal** [FahimF/SQLiteDB#42]
Hello sir when i am adding one more column(name) into Task table then an error has occure.

**INSERT INTO tasks(name, categoryID, task) VALUES (?, ?, ?), Error: table tasks has no column named name**

and please let me know that how do i create a new table in my project. what files i need to use in my project.

Regards
Nitesh

**Comment by FahimF** [comment]
This is not an issue - but a question. It would be better to read the FAQ (which is under the wiki) first and then contact me if your question is not answered there. Please do take a look at the FAQ since your question is answered there:
https://github.com/FahimF/SQLiteDB/wiki/FAQs
