### ISSUE TITLE
update affected rows bug

### ISSUE THREAD

**Issue by amicwall** [FahimF/SQLiteDB#44]
1) create table mytable(mykey INTEGER,myvalue INTEGER)
2) insert into mytable("mykey","myvalue") values(100,10)
3) update mytable set myvalue=20 where mykey=500
        nothing is changed in the table (as expected), but the return value is 1 instead of 0
        see SQLiteDB.swift: var cnt = sqlite3_changes(self.db)

**Comment by amicwall** [comment]
the problem line is: 			if cnt == 0 { cnt += 1 } 
The issue is that 0 is defined as FAIL for the execute statement, but 0 is a valid statement result when an update does not affect any rows. A solution would be to define FAIL as -1, and >=0 as success, then you can get rid of "cnt += 1"

**Comment by FahimF** [comment]
Actually, that's not a bug per se. If you read the documentation for the execute method, it does not say that it returns the count of the updated rows. It returns a status indicating success or failure. It does return the ID of the inserted record for INSERT statements but does not actually make any effort to return the number of updated records for an UPDATE statement. If this is useful perhaps I might look at a mechanism to handle this in the future, but getting the update count is not supported at the moment.

**Comment by amicwall** [comment]
well I find it very useful, so I made the change in my implementation to return the number of affected rows. Btw, the GRDB framework supports this, but I prefer using your project, so thanks
