### ISSUE TITLE
How to implement a one-to-many association table ?

### ISSUE THREAD

**Issue by Jinxiansen** [FahimF/SQLiteDB#45]

**Comment by scinfu** [comment]
+1

**Comment by FahimF** [comment]
Not quite sure what you mean? Do you mean you want to support associations via SQLTable? If yes, then you would have to code the support in via the SQLTable sub-class. There are no plans at the moment to provide support for this via SQLTable. But this might change in the future depending on the circumstances.

**Comment by Jinxiansen** [comment]
![a](https://cloud.githubusercontent.com/assets/16829428/25175561/cf244e8c-252d-11e7-85ef-e466d632e296.png)

Hello, I found this method in SQLite.Swift, so switch to the embrace of SQLite.Swift.
Goodbye, good luck!
🖖🏿🖖🏿🖖🏿
