### ISSUE TITLE
Blob

### ISSUE THREAD

**Issue by DavidTomic** [FahimF/SQLiteDB#49]
How to save, retrieve blob ?

**Comment by FahimF** [comment]
If you are using SQLTable, simply define properties of Data type. If you are using SQLiteDB directly, then pass a Data value to the relevant query.

**Comment by DavidTomic** [comment]
I got it working.

I had to use db.execute(sql: String, parameters: [Any]?) instead of db.execute(sql: String)

Thank you for help.
