### ISSUE TITLE
not support xcode 9

### ISSUE THREAD

**Issue by icecooly** [FahimF/SQLiteDB#50]
![1](https://user-images.githubusercontent.com/3367934/28306873-9c69bdd2-6bd3-11e7-800a-781b201deef5.png)

**Comment by icecooly** [comment]
xcode 8.3.2 is ok

**Comment by jmanoel** [comment]
Here compiled well. Could you check if you added the sqlite3.h on the Build Phases on your project. Go to Build Phases -> Link Binary With Libraries.

**Comment by icecooly** [comment]
let me try . thanks
