### ISSUE TITLE
Table Relations

### ISSUE THREAD

**Issue by lucascorrea** [FahimF/SQLiteDB#60]
Hi everyone,

Would like to know if this library there is a support to Table relationships?

For example:

```
class Employee:SQLTable {
	var id = -1
	var name = ""
        var address = Address()
}

class Address:SQLTable {
	var id = -1
	var street = ""
        var number = ""
}
```

**Comment by FahimF** [comment]
The library itself does not provide any support for relationships. But when I use SQLiteDB myself, I simply add a computed variable named `address` (as per your above example) which would encapsulate the necessary query to fetch the records, something like:

```
var address: [Address] {
    return Address.rows(filter: "employeeID = \(id)")
}
```

Of course, the above assumes that the `Address` table has an `employeeID` column to set up the relationship between the two tables. If that is not the case, then your code would, obviously, need to be modified accordingly :)
